[package]
name = "cpu_intensive_extension"
version = "0.1.0"
edition = "2021"

[lib]
name = "cpu_intensive_extension"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.0", features = ["extension-module"] }
